# DISRADU_DOWN configuration file

NAME: "DISRADU_DOWN"
GROUP_NAME: "DISRADU"
NUM_CHANNELS: 15
TYPE: "planar"
CHANNEL_TAGS: ['DISRADU01', 'DISRADU02','DISRADU03', 'DISRADU04', 'DISRADU05', 'DISRADU06',
               'DISRADU07', 'DISRADU08', 'DISRADU09', 'DISRADU10', 'DISRADU11', 'DISRADU12',
               'DISRADU13', 'DISRADU14', 'DISRADU15']

BUILD_TYPE: "FROM PRIMITIVES" # Build the camera from primitives, not using a CAD file
SLIT_WIDTH: 0.003  # 3 mm slit (circular)
SLIT_HEIGHT: 0.003 # 3 mm slit (circular)
FOIL_WIDTH: 0.005  # width of the diode
FOIL_HEIGHT: 0.002  # height of the diode
FOIL_CORNER_CURVATURE: 0.0005
SLIT_SENSOR_SEPARATION: 0.0305  # 2.98 cm between the slit and the diode array
FOIL_SEPARATION: 0.00212  # 2.12 mm between diodes
FOIL_POSITIONS: [6.5, 5.5, 4.5, 3.5, 2.5, 1.5, 0.5, -0.5, -1.5,
                -2.5, -3.5, -4.5, -5.5, -6.5, -7.5] # Foil shift relative to the center of the sensor
# This is where the center of the diode is, example: 0.5 * FOIL_SEPARATION

# Disrad toroidal location is at 225R+1, switched to 210R+1 in 2010, switched back to 225R+1 in 2018.
# Location in Emis3D = 360 - 225.0 = 135.0
CAMERA_POSITION_R_Z_PHI: [2.3, 0.74, 135.0] # R, z position of the camera (slit)
# NOTE: Phi is in degrees in Emis3D coordinates = 360 - DIII-D coordinates
CAMERA_ROTATION: 152.3 # Rotate the camera this amount, in degrees, towards R=0, z=0
CAMERA_DOWNWARD_FACING: True # True for -z cameras, False for +z cameras (RM on DIII-D)

# Optional stuff below!

# Chord information, testing/sxr_chords.py uses this to make sure that everything is correct
r0:   [2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3,
       2.3, 2.3]
rf:   [2.21, 2.09, 1.97, 1.82, 1.63, 1.47, 1.29, 1.12, 1.02, 1.02, 1.02,
       1.02, 1.02, 1.02, 1.02]
z0:   [0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74, 0.74,
       0.74, 0.74, 0.74, 0.74]
zf:   [-0.78, -0.99, -1.07, -1.15, -1.36, -1.36, -1.36, -1.33, -1.18,
       -0.94, -0.73, -0.56, -0.4 , -0.27, -0.14]
